schema: ./graphql/schema.graphql
documents: ''
extensions:
  codegen:
    generates:
      ./graphql.schema.json:
        plugins:
          - introspection
      ./types/graphql.tsx:
        plugins:
          - typescript
          - typescript-operations
          - typescript-react-apollo
    overwrite: true
