
enum Size{
  XS
  S
  M
  L
  XL
}

type Species{
  name: String!
  scientificName: String
  edible: Boolean
  produces: Boolean
  notes: String
  icon: String!
  findings: [Finding!] @relation
}

type Finding{
  species: Species
  size: Size!
  producing: Boolean
  lat: Float!
  long: Float!
  notes: String
  harvests: [Harvest!] @relation
}

type Harvest{
  finding: Finding
  notes: String
}

type Query {
  findings: [Finding!]!
  species: [Species!]!
  harvests: [Harvest!]!
}
